server:
  port: 23456

spring:
  application:
    name: canteen-simulation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/canteen_simulation_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: canteen_simulation
    password: canteen_simulation
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true